### PR TITLE
feat: allow GitHub compare API

### PR DESCRIPTION
**Pull request by erezrokah**
Due to a [recent change in Netlify CMS](https://github.com/netlify/netlify-cms/pull/2975/files#diff-18378ab822bf2d64f8822c62d7d915e7R886), we are using the GitHub [compare API](https://developer.github.com/v3/repos/commits/#compare-two-commits) to rebase branches.

Not sure how to go about testing it locally.

### CODE REVIEW

**Comment by mraerino** [comment]
I can provide you with a staging deployment of this PR. Would that help?

**Comment by erezrokah** [comment]
That would be perfect

**Comment by erezrokah** [comment]
I tried running the `git-gateway` binary after build it locally, but not sure how to set up the environment variables to get passed authentication

**Comment by mraerino** [comment]
Using a repo-local branch: https://github.com/netlify/git-gateway/tree/feat/allow_github_compare_api

**Pull request merged**
